export const UPGRADE_CONFIG = [
  {
    id: 'mouse',
    name: 'Компьютерная мышь',
    basePrice: 50,
    clickBonus: 1,
    viewerBonus: 1,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'twitch_pad',
    name: 'Коврик для мыши',
    basePrice: 150,
    clickBonus: 2,
    viewerBonus: 1,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'keyboard',
    name: 'Клавиатура',
    basePrice: 250,
    clickBonus: 4,
    viewerBonus: 1,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'headphones',
    name: 'Наушники',
    basePrice: 450,
    clickBonus: 5,
    viewerBonus: 1,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'microphone',
    name: 'Микрофон',
    basePrice: 550,
    clickBonus: 7,
    viewerBonus: 2,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'monitor',
    name: 'Монитор',
    basePrice: 1500,
    clickBonus: 10,
    viewerBonus: 2,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'case',
    name: 'Корпус',
    basePrice: 1600,
    clickBonus: 12,
    viewerBonus: 2,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'motherboard',
    name: 'Материнская плата',
    basePrice: 3300,
    clickBonus: 14,
    viewerBonus: 2,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'ram',
    name: 'Оперативная память',
    basePrice: 2950,
    clickBonus: 16,
    viewerBonus: 3,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'psu',
    name: 'Блок питания',
    basePrice: 2400,
    clickBonus: 20,
    viewerBonus: 3,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'ssd',
    name: 'Память SSD',
    basePrice: 3900,
    clickBonus: 25,
    viewerBonus: 3,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'm2_drive',
    name: 'Накопитель M2',
    basePrice: 6500,
    clickBonus: 35,
    viewerBonus: 4,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'cpu',
    name: 'Процессор',
    basePrice: 7000,
    clickBonus: 45,
    viewerBonus: 4,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'water_cooling',
    name: 'Водяное охлаждение',
    basePrice: 4450,
    clickBonus: 60,
    viewerBonus: 4,
    priceMultiplier: 1.3,
    stackable: true,
  },
  {
    id: 'gpu',
    name: 'Видеокарта',
    basePrice: 9930,
    clickBonus: 70,
    viewerBonus: 5,
    priceMultiplier: 1.3,
    stackable: true,
  }
];
